FROM node:16-alpine as builder
ENV PROJECT_ENV production
ENV NODE_ENV production
COPY package*.json /app/
WORKDIR /app
RUN npm install --production=false
COPY . /app
RUN npm run build

FROM lipanski/docker-static-website:latest
COPY --from=builder /app/build .
CMD ["/thttpd", "-D", "-h", "0.0.0.0", "-p", "3000", "-d", "/home/static", "-u", "static", "-l", "-", "-M", "60"]