FROM node:16-alpine as builder
COPY package*.json /app/
WORKDIR /app
RUN npm install
COPY . /app
RUN npm run build

FROM alpine:latest
RUN apk add lighttpd
COPY config/lighttpd.conf .
COPY --from=builder /app/build /var/www/app1/
CMD ["lighttpd", "-D", "-f", "lighttpd.conf"]